### ISSUE TITLE
[feature request] specify all defaults in one call, like commander

### ISSUE THREAD

**Issue by jtprince** [matheusmoreira/acclaim#3]
Defaults are often grouped together in a hash and stored in some class constant.  The current code requires that defaults be set individually for each option (which is good).  But in some cases it is far more DRY to be able to specify all the defaults at once, perhaps before any other individual options are given.

(see commander for an example of this behavior)

**Comment by matheusmoreira** [comment]
This is something I've been meaning to implement. All modules under `Option::Type` already respond to a `default` method, which return the "default default value" for the type.

All that is missing is a way to register the default values for each class. Since there is no way to pass two blocks at once, I was thinking about redesigning the type registration DSL:

```
Acclaim::Option::Type.accept MyClass do
  # instance_eval

  handle do |string|
    MyClass.parse string
  end

  default do
    MyClass.new
  end

end
```

While directly storing the object is fine for simple objects such as numbers, the abstraction will probably break down when things that depend on time and date need to be implemented since the default value will be created during initialization.

What are your thoughts?

By the way, if you need to pass the same default value to multiple options, [`Ribbon::Options`](https://github.com/matheusmoreira/ribbon/blob/master/lib/ribbon/options.rb) has got you covered:

```
class Application::Command < Acclaim::Command

  option_scope default: 10, arity: [1, -1] do
    option :an, Integer       # default: 10, arity: [1, -1]
    option :another, Integer  # default: 10, arity: [1, -1]
  end

end
```

**Comment by jtprince** [comment]
I'm not sure we are thinking of exactly the same thing (my original feature request was not very detailed, my apologies).  I am thinking of defaults that map onto the option by name, like in this example (I'm using made up syntax, of course, but it will hopefully illustrate the point):

```
SomeCommand < Acclaim::Command 
  defaults( { col_size: 23, color: "red", slipperyness: :very } )
  opt :col_size, "the number of columns"
  opt :color, "the color of your dog"
  opt :slipperyness, "how slippery is the slide"
end
```

What that allows you to do is bring over defaults from some other class very easily:

```
SomeOtherClass
  DEFAULTS = { col_size: 23, color: "red", slipperyness: :very }
end

SomeCommand < Acclaim::Command 
  defaults SomeOtherClass::DEFAULTS
  opt :col_size, "the number of columns"
  ...
end
```

The alternative is doing something like this, but it is a little wordy and not very DRY:

```
SomeCommand < Acclaim::Command 
  opt :col_size, "the number of columns", :default => SomeOtherClass::DEFAULT[:col_size]
  opt :color, "the color of your dog", :default => SomeOtherClass::DEFAULT[:color]
  opt :slipperyness, "how slippery is the slide", :default => SomeOtherClass::DEFAULT[:slipperyness]
end
```

Maybe that will help to make sure we are talking about the same thing.

The option_scope example is quite cool, btw.  (ditto the whole ribbon gem)

**Comment by matheusmoreira** [comment]
I understand now. It is a reasonable feature. I've implemented it for commands and apparently it works fine:

```
class App::Cmd < Acclaim::Command
  defaults option_key: 'default value'
  option :option_key, arity: [0, -1]
end

class App::Cmd::Subcmd < App::Cmd
  # defaults is an alias for option_defaults
  option_defaults App::Cmd.option_defaults
end
```

Similar functionality can be implemented with option sets if and when that gets done.

I also took this as an opportunity to move `Command::DSL` methods related to options to `Command::DSL::Options`, thus cleaning up the code.
